#if !canImport(ObjectiveC)
import XCTest

extension LogTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogTests = [
        ("testEnabled", testEnabled),
        ("testLevel", testLevel),
        ("testLog", testLog),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LogTests.__allTests__LogTests),
    ]
}
#endif
